apiVersion: v2

name: cert-manager
description: Umbrella

type: application

version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: cert-manager
    version: v1.7.3
    repository: https://charts.jetstack.io