apiVersion: v1
kind: Pod
metadata:
  name: kafka-perf
spec:
  containers:
    - name: kafka-perf
      image: bitnami/kafka:latest
      command:
        - /bin/bash
        - -c
      args:
        - |
          while true ; do
            true;
          done