apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: data
driver: pd.csi.storage.gke.io
deletionPolicy: Delete
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: data
spec:
  volumeSnapshotClassName: data
  source:
    persistentVolumeClaimName: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot0
spec:
  dataSource:
    name: data
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: premium-rwo
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot1
spec:
  dataSource:
    name: data
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: premium-rwo
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot2
spec:
  dataSource:
    name: data
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: premium-rwo
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot3
spec:
  dataSource:
    name: data
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: premium-rwo
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot4
spec:
  dataSource:
    name: data
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: premium-rwo
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot5
spec:
  dataSource:
    name: data
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: premium-rwo
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot6
spec:
  dataSource:
    name: data
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: premium-rwo
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot7
spec:
  dataSource:
    name: data
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: premium-rwo
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot8
spec:
  dataSource:
    name: data
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: premium-rwo
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot9
spec:
  dataSource:
    name: data
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: premium-rwo
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi