apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: data
driver: pd.csi.storage.gke.io
deletionPolicy: Delete
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: data
spec:
  volumeSnapshotClassName: data
  source:
    persistentVolumeClaimName: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapshot2
spec:
  dataSource:
    name: data
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  storageClassName: premium-rwo
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi