apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: redpanda
spec:
  image: "vectorized/redpanda"
  version: "latest"
  replicas: 3
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9644"
    prometheus.io/path: "/metrics"
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
  storage:
    capacity: 100Gi
    storageClassName: premium-rwo
  configuration:
    rpcServer:
      port: 33145
    kafkaApi:
      - port: 9092
    pandaproxyApi:
      - port: 8082
    schemaRegistry:
      port: 8081
    adminApi:
      - port: 9644
    developerMode: true